//! TypeScript code generator for the Blueberry IDL.
//!
//! Emits two files:
//! - `typescript/blueberry_messages.ts` — all interfaces, enums, structs, consts, and
//!   `<Name>Message` classes with explicit `encode`/`decode` bodies that call into
//!   `blueberry-serde-ts`'s `BlueberryWriter` / `BlueberryReader`.
//! - `typescript/index.ts` — barrel re-export plus the `DecodedMessage` discriminated
//!   union and `decodeMessage(bytes)` registry keyed on `(moduleKey << 16) | messageKey`.
//!
//! Mirrors the architectural split established by the Rust and Python targets: every
//! wire-format rule lives in the `blueberry-serde-ts` runtime, never in generated code.

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;

use blueberry_ast::{Annotation, AnnotationParam, ConstValue, Definition, Type};
use blueberry_codegen_core::{CodegenError, DEFAULT_MODULE_KEY, GeneratedFile, TypeRegistry};

mod consts;
mod enums;
mod messages;
mod naming;
mod structs;

use naming::{camel_case, pascal_case, quoted_string};

const MESSAGES_FILE: &str = "typescript/blueberry_messages.ts";
const INDEX_FILE: &str = "typescript/index.ts";
const RUNTIME_PACKAGE: &str = "blueberry-serde-ts";

/// Generate TypeScript code for the provided IDL definitions.
pub fn generate(definitions: &[Definition]) -> Result<Vec<GeneratedFile>, CodegenError> {
    let generator = TypeScriptGenerator::new(definitions);
    generator.generate_files(definitions)
}

pub(crate) struct TypeScriptGenerator {
    pub(crate) registry: TypeRegistry,
}

#[derive(Clone)]
#[allow(dead_code)]
pub(crate) struct MessageEntry {
    pub class_name: String,
    pub fields_name: String,
    pub topic_const_name: String,
    pub topic_template: String,
    pub module_key: u16,
    pub message_key: u16,
}

impl TypeScriptGenerator {
    fn new(definitions: &[Definition]) -> Self {
        Self {
            registry: TypeRegistry::new(definitions),
        }
    }

    fn generate_files(
        &self,
        definitions: &[Definition],
    ) -> Result<Vec<GeneratedFile>, CodegenError> {
        let mut imports: BTreeSet<&'static str> = BTreeSet::new();
        imports.insert("BlueberryWriter");
        imports.insert("BlueberryReader");
        imports.insert("MessageHeader");
        imports.insert("serializeMessage");
        imports.insert("deserializeMessage");

        let mut body = String::new();
        let mut message_entries: Vec<MessageEntry> = Vec::new();
        let mut key_gen = MessageKeyGen::default();

        self.emit_definitions(
            definitions,
            &mut Vec::new(),
            None,
            &mut body,
            &mut imports,
            &mut message_entries,
            &mut key_gen,
        )?;

        validate_unique_message_keys(&message_entries)?;

        let mut header = String::new();
        header.push_str("// Auto-generated by blueberry-generator-typescript. Do not edit.\n\n");
        header.push_str("/* eslint-disable */\n");
        header.push_str("/* prettier-ignore */\n\n");
        header.push_str(&format_imports(RUNTIME_PACKAGE, &imports));
        header.push('\n');

        let mut messages_contents = header;
        messages_contents.push_str(&body);

        let index_contents = self.emit_index(&message_entries);

        Ok(vec![
            GeneratedFile {
                path: MESSAGES_FILE.to_string(),
                contents: messages_contents,
            },
            GeneratedFile {
                path: INDEX_FILE.to_string(),
                contents: index_contents,
            },
        ])
    }

    #[allow(clippy::too_many_arguments)]
    fn emit_definitions(
        &self,
        defs: &[Definition],
        scope: &mut Vec<String>,
        parent_module_key: Option<u16>,
        body: &mut String,
        imports: &mut BTreeSet<&'static str>,
        messages: &mut Vec<MessageEntry>,
        key_gen: &mut MessageKeyGen,
    ) -> Result<(), CodegenError> {
        for def in defs {
            match def {
                Definition::ModuleDef(module) => {
                    let mk =
                        annotation_u16(&module.annotations, "module_key").or(parent_module_key);
                    scope.push(module.node.name.clone());
                    self.emit_definitions(
                        &module.node.definitions,
                        scope,
                        mk,
                        body,
                        imports,
                        messages,
                        key_gen,
                    )?;
                    scope.pop();
                }
                Definition::ConstDef(const_def) => {
                    let rendered = self.emit_const(const_def, scope);
                    if !rendered.is_empty() {
                        body.push_str(&rendered);
                        body.push('\n');
                    }
                }
                Definition::TypeDef(typedef_def) => {
                    let rendered = self.emit_typedef(typedef_def, scope);
                    if !rendered.is_empty() {
                        body.push_str(&rendered);
                        body.push('\n');
                    }
                }
                Definition::EnumDef(enum_def) => {
                    let rendered = self.emit_enum(enum_def);
                    body.push_str(&rendered);
                    body.push('\n');
                }
                Definition::StructDef(struct_def) => {
                    let rendered = self.emit_struct(struct_def, scope);
                    body.push_str(&rendered);
                    body.push('\n');
                }
                Definition::MessageDef(message_def) => {
                    let module_key = annotation_u16(&message_def.annotations, "module_key")
                        .or(parent_module_key)
                        .unwrap_or(DEFAULT_MODULE_KEY);
                    let message_key = annotation_u16(&message_def.annotations, "message_key")
                        .unwrap_or_else(|| key_gen.next());
                    let entry = self.emit_message(
                        message_def,
                        scope,
                        module_key,
                        message_key,
                        body,
                        imports,
                    )?;
                    if let Some(entry) = entry {
                        messages.push(entry);
                    }
                }
                Definition::ImportDef(_) => {}
            }
        }
        Ok(())
    }

    fn emit_index(&self, messages: &[MessageEntry]) -> String {
        let mut out = String::new();
        out.push_str("// Auto-generated by blueberry-generator-typescript. Do not edit.\n\n");
        out.push_str("/* eslint-disable */\n");
        out.push_str("/* prettier-ignore */\n\n");
        out.push_str("export * from './blueberry_messages.js';\n\n");

        if messages.is_empty() {
            return out;
        }

        let runtime_imports = ["MessageHeader"];
        out.push_str(&format!(
            "import {{ {imports} }} from '{pkg}';\n",
            imports = runtime_imports.join(", "),
            pkg = RUNTIME_PACKAGE,
        ));

        let message_imports: Vec<String> = messages
            .iter()
            .flat_map(|entry| {
                vec![
                    entry.class_name.clone(),
                    format!("type {}", entry.fields_name),
                ]
            })
            .collect();
        let imports_block = message_imports.join(",\n  ");
        out.push_str(&format!(
            "import {{\n  {imports},\n}} from './blueberry_messages.js';\n\n",
            imports = imports_block,
        ));

        out.push_str("export type DecodedMessage =\n");
        for entry in messages {
            let kind = pascal_case(entry.class_name.trim_end_matches("Message"));
            out.push_str(&format!(
                "  | {{ kind: {kind}; header: MessageHeader; fields: {fields} }}\n",
                kind = quoted_string(&kind),
                fields = entry.fields_name,
            ));
        }
        out.push_str("  | { kind: 'Unknown'; header: MessageHeader; body: Uint8Array };\n\n");

        out.push_str("export function decodeMessage(bytes: Uint8Array): DecodedMessage {\n");
        out.push_str("  const header = MessageHeader.decode(bytes);\n");
        out.push_str("  if (!header) {\n");
        out.push_str("    return { kind: 'Unknown', header: new MessageHeader(0, 0, 0, 0, 0), body: bytes };\n");
        out.push_str("  }\n");
        out.push_str("  const key32 = (((header.moduleKey & 0xffff) << 16) >>> 0) | (header.messageKey & 0xffff);\n");
        out.push_str("  switch (key32) {\n");

        for entry in messages {
            let combined = ((entry.module_key as u32) << 16) | entry.message_key as u32;
            let kind = pascal_case(entry.class_name.trim_end_matches("Message"));
            out.push_str(&format!("    case 0x{:08x}: {{\n", combined,));
            out.push_str(&format!(
                "      const decoded = {class}.decode(bytes);\n",
                class = entry.class_name,
            ));
            out.push_str(&format!(
                "      return {{ kind: {kind}, header: decoded.header, fields: decoded.fields }};\n",
                kind = quoted_string(&kind),
            ));
            out.push_str("    }\n");
        }

        out.push_str("    default:\n");
        out.push_str("      return { kind: 'Unknown', header, body: bytes };\n");
        out.push_str("  }\n");
        out.push_str("}\n");

        out
    }

    /// Convert a resolved IDL `Type` into a TypeScript type expression.
    pub(crate) fn render_ts_type(&self, ty: &Type, scope: &[String]) -> String {
        let resolved = self.registry.resolve_type(ty, scope);
        match &resolved {
            Type::Boolean => "boolean".to_string(),
            Type::Octet | Type::Char => "number".to_string(),
            Type::Short
            | Type::UnsignedShort
            | Type::Long
            | Type::UnsignedLong
            | Type::Float
            | Type::Double
            | Type::LongDouble => "number".to_string(),
            Type::LongLong | Type::UnsignedLongLong => "bigint".to_string(),
            Type::String { .. } => "string".to_string(),
            Type::Sequence { element_type, .. } => {
                let inner = self.render_ts_type(element_type, scope);
                let needs_parens =
                    inner.contains(' ') || inner.contains('|') || inner.contains('&');
                if needs_parens {
                    format!("({inner})[]")
                } else {
                    format!("{inner}[]")
                }
            }
            Type::Array {
                element_type,
                dimensions,
            } => {
                let mut elem_ty = self.render_ts_type(element_type, scope);
                for _ in dimensions {
                    let needs_parens =
                        elem_ty.contains(' ') || elem_ty.contains('|') || elem_ty.contains('&');
                    elem_ty = if needs_parens {
                        format!("({elem_ty})[]")
                    } else {
                        format!("{elem_ty}[]")
                    };
                }
                elem_ty
            }
            Type::ScopedName(path) => path
                .last()
                .cloned()
                .map(|name| pascal_case(&name))
                .unwrap_or_else(|| "unknown".to_string()),
            Type::WString | Type::WChar => "string".to_string(),
        }
    }
}

#[derive(Default)]
pub(crate) struct MessageKeyGen {
    next: u16,
}

impl MessageKeyGen {
    pub(crate) fn next(&mut self) -> u16 {
        self.next = self.next.wrapping_add(1);
        if self.next == 0 {
            self.next = 1;
        }
        self.next
    }
}

pub(crate) fn annotation_value<'a>(
    annotations: &'a [Annotation],
    name: &str,
) -> Option<&'a ConstValue> {
    annotations
        .iter()
        .find(|annotation| {
            annotation
                .name
                .last()
                .map(|segment| segment.eq_ignore_ascii_case(name))
                .unwrap_or(false)
        })
        .and_then(|annotation| {
            annotation
                .params
                .iter()
                .map(|param| match param {
                    AnnotationParam::Named { name, value }
                        if name.eq_ignore_ascii_case("value") =>
                    {
                        value
                    }
                    AnnotationParam::Positional(value) => value,
                    AnnotationParam::Named { value, .. } => value,
                })
                .next()
        })
}

pub(crate) fn annotation_string(annotations: &[Annotation], name: &str) -> Option<String> {
    annotation_value(annotations, name).and_then(|value| match value {
        ConstValue::String(value) => Some(value.clone()),
        _ => None,
    })
}

pub(crate) fn annotation_u16(annotations: &[Annotation], name: &str) -> Option<u16> {
    annotation_value(annotations, name).and_then(|value| match value {
        ConstValue::Integer(lit) if (0..=u16::MAX as i128).contains(&lit.value) => {
            Some(lit.value as u16)
        }
        _ => None,
    })
}

/// Reject IDL where two messages collide on the wire-level routing key
/// `(module_key, message_key)`. Without this guard the generated registry
/// switch would silently drop one branch and the second message would be
/// undecodable at runtime.
fn validate_unique_message_keys(messages: &[MessageEntry]) -> Result<(), CodegenError> {
    let mut seen: HashMap<u32, &MessageEntry> = HashMap::new();
    for entry in messages {
        let combined = ((entry.module_key as u32) << 16) | entry.message_key as u32;
        if let Some(first) = seen.get(&combined) {
            return Err(CodegenError::DuplicateMessageKey {
                module_key: entry.module_key,
                message_key: entry.message_key,
                first: first.class_name.clone(),
                second: entry.class_name.clone(),
            });
        }
        seen.insert(combined, entry);
    }
    Ok(())
}

pub(crate) fn scoped_name(scope: &[String], name: &str) -> String {
    if scope.is_empty() {
        name.to_string()
    } else {
        format!("{}::{}", scope.join("::"), name)
    }
}

fn format_imports(package: &str, imports: &BTreeSet<&'static str>) -> String {
    if imports.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    out.push_str("import {\n");
    for name in imports {
        let _ = writeln!(out, "  {name},");
    }
    let _ = writeln!(out, "}} from '{package}';");
    out
}

/// Emit a writer-call for a single named field. Produces a single statement (or
/// a block when sequences/structs need a loop). Handles every type the runtime
/// understands; unresolvable scoped names fall back to a TODO-marker.
pub(crate) fn emit_write_for_member(
    tsgen: &TypeScriptGenerator,
    w_var: &str,
    accessor: &str,
    ty: &Type,
    scope: &[String],
    indent: &str,
) -> String {
    let resolved = tsgen.registry.resolve_type(ty, scope);
    emit_write_call(tsgen, w_var, accessor, &resolved, scope, indent)
}

pub(crate) fn emit_write_call(
    tsgen: &TypeScriptGenerator,
    w_var: &str,
    accessor: &str,
    resolved: &Type,
    scope: &[String],
    indent: &str,
) -> String {
    match resolved {
        Type::Boolean => format!("{indent}{w_var}.writeBool({accessor});\n"),
        Type::Octet | Type::Char => format!("{indent}{w_var}.writeU8({accessor});\n"),
        Type::Short => format!("{indent}{w_var}.writeI16({accessor});\n"),
        Type::UnsignedShort => format!("{indent}{w_var}.writeU16({accessor});\n"),
        Type::Long => format!("{indent}{w_var}.writeI32({accessor});\n"),
        Type::UnsignedLong => format!("{indent}{w_var}.writeU32({accessor});\n"),
        Type::LongLong => format!("{indent}{w_var}.writeI64({accessor});\n"),
        Type::UnsignedLongLong => format!("{indent}{w_var}.writeU64({accessor});\n"),
        Type::Float => format!("{indent}{w_var}.writeF32({accessor});\n"),
        Type::Double | Type::LongDouble => format!("{indent}{w_var}.writeF64({accessor});\n"),
        Type::String { .. } | Type::WString => {
            format!("{indent}{w_var}.writeString({accessor});\n")
        }
        Type::Sequence { element_type, .. } | Type::Array { element_type, .. } => {
            let elem_idx = unique_var("elem", accessor);
            let seq_var = unique_var("seq", accessor);
            let mut out = String::new();
            let _ = write!(
                out,
                "{indent}{{\n{indent}  const {seq} = {w}.beginSequence();\n",
                seq = seq_var,
                w = w_var,
            );
            let _ = writeln!(
                out,
                "{indent}  for (const {elem} of {acc} ?? []) {{",
                elem = elem_idx,
                acc = accessor,
            );
            let _ = writeln!(
                out,
                "{indent}    {seq}.writeElement((sw) => {{",
                seq = seq_var,
            );
            let resolved_elem = tsgen.registry.resolve_type(element_type, scope);
            let inner_indent = format!("{indent}      ");
            out.push_str(&emit_write_call(
                tsgen,
                "sw",
                &elem_idx,
                &resolved_elem,
                scope,
                &inner_indent,
            ));
            let _ = writeln!(out, "{indent}    }});");
            let _ = write!(
                out,
                "{indent}  }}\n{indent}  {seq}.end();\n{indent}}}\n",
                seq = seq_var
            );
            out
        }
        Type::ScopedName(path) => {
            if let Some(base) = tsgen.registry.enum_base(path) {
                let casted = format!("({} as number)", accessor);
                emit_write_call(tsgen, w_var, &casted, base, scope, indent)
            } else if let Some(struct_path) = tsgen.registry.resolve_struct(path, scope) {
                let members = tsgen.registry.collect_struct_members(&struct_path);
                let mut sorted = members.clone();
                tsgen.registry.sort_members_by_alignment(&mut sorted);
                let mut out = String::new();
                let _ = writeln!(out, "{indent}{{");
                let inner = format!("{indent}  ");
                for member in &sorted {
                    let sub_accessor = format!("{}.{}", accessor, camel_case(&member.name));
                    out.push_str(&emit_write_call(
                        tsgen,
                        w_var,
                        &sub_accessor,
                        &member.ty,
                        &struct_path,
                        &inner,
                    ));
                }
                let _ = writeln!(out, "{indent}}}");
                out
            } else {
                format!(
                    "{indent}// TODO: write unresolved scoped name {}\n",
                    path.join("::")
                )
            }
        }
        Type::WChar => format!("{indent}{w_var}.writeU8({accessor});\n"),
    }
}

pub(crate) fn emit_read_for_member(
    tsgen: &TypeScriptGenerator,
    r_var: &str,
    ty: &Type,
    scope: &[String],
) -> String {
    let resolved = tsgen.registry.resolve_type(ty, scope);
    emit_read_expr(tsgen, r_var, &resolved, scope)
}

pub(crate) fn emit_read_expr(
    tsgen: &TypeScriptGenerator,
    r_var: &str,
    resolved: &Type,
    scope: &[String],
) -> String {
    match resolved {
        Type::Boolean => format!("{r_var}.readBool()"),
        Type::Octet | Type::Char => format!("{r_var}.readU8()"),
        Type::Short => format!("{r_var}.readI16()"),
        Type::UnsignedShort => format!("{r_var}.readU16()"),
        Type::Long => format!("{r_var}.readI32()"),
        Type::UnsignedLong => format!("{r_var}.readU32()"),
        Type::LongLong => format!("{r_var}.readI64()"),
        Type::UnsignedLongLong => format!("{r_var}.readU64()"),
        Type::Float => format!("{r_var}.readF32()"),
        Type::Double | Type::LongDouble => format!("{r_var}.readF64()"),
        Type::String { .. } | Type::WString => format!("{r_var}.readString()"),
        Type::Sequence { element_type, .. } | Type::Array { element_type, .. } => {
            let resolved_elem = tsgen.registry.resolve_type(element_type, scope);
            let ts_elem_ty = tsgen.render_ts_type(&resolved_elem, scope);
            let read_call = emit_read_expr(tsgen, "sr", &resolved_elem, scope);
            format!(
                "(() => {{ const seq = {r}.beginSequence(); const out: {ty}[] = []; for (let i = 0; i < seq.count; i++) {{ out.push(seq.readElement((sr) => ({read}))); }} return out; }})()",
                r = r_var,
                ty = ts_elem_ty,
                read = read_call,
            )
        }
        Type::ScopedName(path) => {
            if let Some(base) = tsgen.registry.enum_base(path) {
                let inner = emit_read_expr(tsgen, r_var, base, scope);
                let enum_name = path
                    .last()
                    .cloned()
                    .map(|n| pascal_case(&n))
                    .unwrap_or_else(|| "unknown".to_string());
                format!("({inner}) as {enum_name}")
            } else if let Some(struct_path) = tsgen.registry.resolve_struct(path, scope) {
                let members = tsgen.registry.collect_struct_members(&struct_path);
                let mut sorted = members.clone();
                tsgen.registry.sort_members_by_alignment(&mut sorted);
                let mut field_inits = Vec::new();
                for member in &sorted {
                    let value = emit_read_for_member(tsgen, r_var, &member.ty, &struct_path);
                    field_inits.push(format!("{}: {}", camel_case(&member.name), value));
                }
                format!("{{ {} }}", field_inits.join(", "))
            } else {
                format!(
                    "/* TODO: unresolved {} */ ({} as any)",
                    path.join("::"),
                    r_var
                )
            }
        }
        Type::WChar => format!("{r_var}.readU8()"),
    }
}

fn unique_var(prefix: &str, accessor: &str) -> String {
    let suffix: String = accessor
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect();
    if suffix.is_empty() {
        prefix.to_string()
    } else {
        let cap = suffix.len().min(8);
        format!("{prefix}_{}", &suffix[..cap])
    }
}
